version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/Akwab-Api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/Akwab-Front"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"